### ISSUE TITLE
Ponyo won't install in python 3.9

### ISSUE THREAD

**Issue by ben-heil** [greenelab/ponyo#28]
Tensorflow has [a weird thing](https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow) where only certain versions will install if you're not using python 3.5-3.8. This isn't an issue with Ponyo so much as an issue with Tensorflow, but it may be worth adding a comment in the README about which version you used (or [specify a python version in the setup](https://stackoverflow.com/questions/37216560/how-can-i-specify-a-python-version-using-setuptools))

**Comment by ajlee21** [comment]
Thank you for checking this. I have added this as a requirement here: https://github.com/greenelab/ponyo/pull/32
