### ISSUE TITLE
`basedir` set within function for `train_vae_modules.train_vae()`

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/ponyo#43]
Hello!

I'm working on automating sophie, which uses ponyo in some places. One function that uses ponyo in the sophie workflow is `train_vae_modules.train_vae()`. I noticed when working with this command that the `base_dir` is set within the fucntion and not exposed to the user:

https://github.com/greenelab/ponyo/blob/master/ponyo/train_vae_modules.py#L132 (reproduced in the code block below)
```
base_dir = os.path.abspath(os.path.join(os.getcwd(), "../"))
```

I think with this written this way, the output of this function will always be one level up from where the user is executing ponyo. Is it possible to change this so that `base_dir` is a user-controlled parameter in the input function? I think it would be fine to have it how it currently is as the default if the user doesn't set one, but having it hard coded as one level up from where the function runs is interfering with my ability to automate the sophie workflow in a snakemake workflow.

**Comment by ajlee21** [comment]
That's a good suggestion. I did not think about the case of a user wanting to adjust the base directory. In that case, maybe we can have the user specify the base dir in the config file, and if its not then define it as one level up from where the function runs. Does that sound ok?

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/ponyo/pull/46
